### ISSUE TITLE
Publish osx-x64 with signing

### ISSUE THREAD

**Issue by Kromtec** [Kromtec/LegendsViewer-Next#11]
@vespakoen It worked! The MacOs pipeline successfully ran through :-) 
Can you try it out if everything works as intended?

**Comment by vespakoen** [comment]
It seemed to work but the notarization actually failed, apparently it is not possible to just throw an executable into a zip and notarize it, it has to be a .app or .dmg, I created an .app in another PR, hope that works ;)

**Comment by Kromtec** [comment]
The pipeline did not fail, so hopefully it works now as an app 😄
Do you think something similar will also be the case under linux? I only tried it with dotnet run but not after publishing.

**Comment by vespakoen** [comment]
Linux should work just fine without any of these signing ceremonies ;)

**Comment by Kromtec** [comment]
This message indicates that **Gatekeeper** (macOS’s security feature) hasn’t fully verified the app despite it being signed and notarized. Here are some steps to ensure everything is correctly set up for macOS Gatekeeper to recognize your app:

### 1. **Confirm Successful Notarization**
   Although it looks like notarization succeeded, it’s good to confirm by checking if the `.dmg` or `.app` file has the notarization **stapled** to it. Run the following command on your `.dmg` or `.app` file to check:

   ```bash
   spctl -a -vv LegendsViewer.app
   ```

   If notarization is successfully stapled, you’ll see `"accepted"` as part of the output. If not, try stapling it manually:

   ```bash
   xcrun stapler staple LegendsViewer.app
   ```

2. **Check App for Quarantine Attributes**
   Sometimes, even notarized apps can have quarantine attributes that prevent macOS from opening them.

   - Check for quarantine attributes by running:
     ```bash
     xattr /Applications/LegendsViewer.app
     ```
   - If you see `com.apple.quarantine` in the output, remove it by running:
     ```bash
     xattr -rd com.apple.quarantine /Applications/LegendsViewer.app
     ```

3. **Reopen the App**
   - Try reopening the app after clearing any quarantine attributes. If this resolves the issue, it indicates that the notarization didn’t clear all security checks in Gatekeeper.

### 4. **Double-Check Notarization Logs for Warnings**
   Even with successful notarization, sometimes Apple’s notarization service logs minor warnings that could cause Gatekeeper issues.

   - After notarization, Apple emails a link to the notarization log. Review it for any warnings or errors that might indicate additional steps.

### 5. **Restart the System (Optional)**
   Occasionally, macOS Gatekeeper or notarization issues can be resolved with a restart, especially after installing new security updates.

Try these steps, and let me know if any of them work for getting LegendsViewer to open without the Gatekeeper warning!

**Comment by Kromtec** [comment]
I have no idea, thats what ChatGPT came up with 🤪

**Comment by vespakoen** [comment]
Success!!

<img width="328" alt="Screenshot 2024-11-06 at 20 51 33" src="https://github.com/user-attachments/assets/7109e885-3af8-4677-92b2-d4ea7fa563a5">

<img width="1354" alt="Screenshot 2024-11-06 at 20 51 46" src="https://github.com/user-attachments/assets/d7676dba-c5ae-4428-ac00-e8d9b2f6cbad">

**Comment by Kromtec** [comment]
Awesome! Thanks for putting so much effort into getting it to work! 🤩
