### ISSUE TITLE
Unhandled exception on big world

### ISSUE THREAD

**Issue by wiktor-obrebski** [Kromtec/LegendsViewer-Next#27]
I got cryptic error when trying to load attached world.

> Connection id "0HN83MJQABQQ2", Request id "0HN83MJQABQQ2:00000006": An unhandled exception was thrown by the application.

After that, the UI stay on loading screen forever.

I am playing on linux, DF adventure beta branch.

[eternal-realms.zip](https://github.com/user-attachments/files/17728208/eternal-realms.zip)

**Comment by Kromtec** [comment]
Thanks, the problem was not the size of the world, but just that the name of the save had a '-' in it. So the parsing of the timestamp threw an exception. It is fixed in the development branch now and this fix will be in the next release version. :-)
