### ISSUE TITLE
Suggestion: add an [ORIENTATION] filter as an option in the dropdown...

### ISSUE THREAD

**Issue by silverwing235** [Kromtec/LegendsViewer-Next#31]
...when adv. search comes back in. (it was another of the things reliant on certain exports, I guess.) 

I mean, the existence of https://github.com/DFHack/scripts/blob/33c6bce4ada26c7afb06282f287f41110731d71b/gaydar.lua in the... previous period, had left me with strong suspicions if something similar could be wrangled in this context? 

Edit: nearly forgot, thanks for all the work so far!

**Comment by Kromtec** [comment]
Currently this information is not available in the exports. So first address would be the DFHack Github page and add that suggestion there. 
If they can bring this information into the export, I may be able to display it and use it for something like filter and search functionality.
