### ISSUE TITLE
Worlds deleted from disk behave strangely in LV

### ISSUE THREAD

**Issue by beatsbury** [Kromtec/LegendsViewer-Next#35]
Hi. I was experimating with lots of generated worlds and thus had to delete some world export .xml files, just to unclutter my game folder.
However, for world, that was explored in Legends Viewer earlier but was subsequently deleted that way, I can do nothing to get rid of it's bookmark on main screen.

https://github.com/user-attachments/assets/50020ef6-880a-4744-a269-e2b26eb4f936

**Comment by beatsbury** [comment]
To be clear, here's the way to reproduce.
* import world to LV for exploring
* delete world's export .xml file
* voila

**Comment by equanimittyy** [comment]
[#25 ](https://github.com/Kromtec/LegendsViewer-Next/issues/25#issuecomment-2495183086)

Further to this ticket.
